# this is for ansible-galaxy
#
# use with
#  ansible-galaxy install -r requirements.yml -p roles/
#
roles:
  - src: geerlingguy.php
    version: 5.0.1
  - src: geerlingguy.repo-epel
    version: 3.1.1
  - src: geerlingguy.repo-remi
    version: 2.1.0
  - src: geerlingguy.apache
    version: 4.0.0
  - src: geerlingguy.mysql
    version: 4.3.4
  - src: geerlingguy.composer
    version: 1.9.2
