#
- name: Setup Passbolt environment
  hosts: all

  roles:
    - role: geerlingguy.repo-epel
      tags: repos
    - role: geerlingguy.repo-remi
      tags: repos
    - role: geerlingguy.apache
      tags: apache
    - role: geerlingguy.php
      tags: php
    - role: local.php-symlink
      tags: [ php, php-symlink ]
    - role: geerlingguy.mysql
      tags: mysql
    - role: geerlingguy.composer
      tags: [ php, composer ]
